Default backends for Daemon and Wallet
monero-ecosystem/monero-python pull request #79
Opened 2021-01-17 21:05 UTC by jeffro256

If no backend is specified, then the backend defaults to
JSONRPCDaemon and JSONRPCWallet for Daemon and Wallet, respectively.
Also if no backend is specified, then any kwargs passed to Daemon
and Wallet initializers will be used to construct a backend with
the default JSONRPC- backends. This will make using Daemon and
Wallet much more seamless for the user.

The following code snippets are functionally identical:

Old:
```
from monero.daemon import Daemon
from monero.backends.jsonrpc import JSONRPCDaemon

daemon1 = Daemon(JSONRPCDaemon())
daemon2 = Daemon(JSONRPCDaemon(host='node.xmr.to'))
```

New:
```
from monero.daemon import Daemon

daemon1 = Daemon()
daemon2 = Daemon(host='node.xmr.to')
```

2021-01-17 21:33 UTC, jeffro256 commented
This PR is backwards-compatible.

2021-01-18 00:33 UTC, emesik requested changes
Nice. I like it. Could you also update docs, please?

2021-01-18 06:23 UTC, jeffro256 commented
I updated the docs. How does it look?

2021-01-18 09:10 UTC, emesik commented
Good! I'll elaborate a bit more on replacable backends, perhaps creating another chapter on that.

2021-01-18 09:10 UTC, merged